### ISSUE TITLE
Sipjs 0.20.0

### ISSUE THREAD

**Issue by mustafaecentrix** [ccabrerar/ViciPhone#8]
Hi Sir,

I have some questions:

1. is it working with sipjs 0.20.0 ? I see on latest versions sipjs have some bugfix. 

2. How to add TurnServer with auth username and password?

Thanks

**Comment by ccabrerar** [comment]
Hello,

We only support version 0.15 of sipjs since version 0.16 changes the API dramatically, and I haven't had the chance to reengineer the code to support the new versions.

Changing turnServers is currently not supported per Viciphone, but you can change the contents of vici_phone.js (look for the ```ua_config``` variable and add this object:
```
 sessionDescriptionHandlerFactoryOptions: {
                rtcConfiguration: {
                        iceServers: [{urls: 'stun:stun.l.zoom.com:19302'}]
                },
        }
```
You may add either turn or stun servers as you wish.

At the end, the full ```ua_config``` should look something like this:

```
var ua_config = {
        userAgentString: 'VICIphone 2.1',
        displayName: cid_name,
        uri: sip_uri,
        hackIpInContact: true,
        hackViaTcp: true,
        hackWssInTransport: true,
        authorizationUser: auth_user,
        password: password,
        log: {
                builtinEnabled: true,
                level: "debug",
        },
        transportOptions: {
                traceSip: true,
                wsServers: ws_server,
        },
        autostart: true,
        registerOptions: {
//              expires: 900
        },
        sessionDescriptionHandlerFactoryOptions: {
                rtcConfiguration: {
                        iceServers: [{urls: 'stun:stun.l.zoom.com:19302'}]
                },
        },
}
```

I'm using an example stun server, but you may add/change whatever else.

Please keep in mind this is not a part for Viciphone, but instead you are reconfiguring the sipjs API.

Regards,
